### ISSUE TITLE
Target Token Helper highlights only working for some spells

### ISSUE THREAD

**Issue by kevinhawke** [reonZ/pf2e-toolbelt#16]
PF2e Toolbelt v1.29.2
Pathfinder 2e v5.11.5
Foundry VTT v11.315

When using Target Token Helper for save spells, the damage highlight doesn't always appear. 

I've seen it work with: Scatter Scree, Timber, Electric Arc, Caustic Blast, Frostbite, Flourishing Flora, Floating Flame, Rime Slick

But it doesn't show up for: Puff of Poison, Grim Tendrils, Gritty Wheeze, Chilling Spray, Ignite Fireworks.

I don't see any errors in the console and I've tried making sure the spells are the latest versions from the compendiums.

**Comment by reonZ** [comment]
The reason is because those spells don't have their save tagged as `Basic Save`, which are the only saves that i can be sure of when it comes to the whole double/half/regular damage even though a spell like `Puff of Poison` clearly works as a `Basic Save` when it comes to the damage part, it is not technically a `Basic Save`.

![image](https://github.com/reonZ/pf2e-toolbelt/assets/651462/5b39b3c6-8a79-4a8f-b02b-55cec4c1cff7)
