### ISSUE TITLE
Template targeting without damage

### ISSUE THREAD

**Issue by jbblanchet** [reonZ/pf2e-toolbelt#38]
Hi,

Really appreciate your hard work. Template targeting works great for damage spells, I'm wondering if there's a way to make it work for buffing/debuffing. Classic example we run into all the time is the bard Anthems, because they usually apply to everyone and you mostly need to recast them every single round. Would be nice if the bard could place the template, select every friendly creature, then boom, everyone gets the buff until next turn. Not sure if that's possible or not, but it would be a major improvement to our game automation.

Thanks in advance.

**Comment by reonZ** [comment]
The template targeting feature helps you targets tokens, you are free to do whatever you want with the targets after that. 

There are reasons why what you want shouldn't be implemented:
1. players can't and shouldn't be able to add effects to NPCs, so a big part of the feature wouldn't be compatible with this
2. effects that rely on the origin actor's level have to be dragged onto an actor by the player owning that actor, otherwise, bugs will ensue

So all in all, this is unlikely to see the light of day.
