### ISSUE TITLE
Request: Return simple health pool sharing

### ISSUE THREAD

**Issue by dogstarrb** [reonZ/pf2e-toolbelt#53]
It seems "share health pool" was turned into "be an eidolon", when I was using it for a master token of a troop and attaching several "slaves" to the same token so they shared a health pool, which I honestly thought was the primary use case, with it also being convenient for summoners, not the other way around to such an extent that troops were made impossible for the sake of making it more eidolon helpful. Maybe a separate feature that works the old way for non-linked tokens?

**Comment by reonZ** [comment]
The reason i imposed the "linked" is because i need to access the actors synchronously for everything to work, but after reading your request, i realize that it was possible to access unlinked actors asynchronously, just not as straight forward.

With the next update, you will be able to have unlinked actor selecting a master, it will also be possible for a master to have more than one "slave" (which wasn't possible in this version.

NOTE: the master still needs to be a linked actor though
