### ISSUE TITLE
[Feature Request] Template Helper support on Gridless and Hex maps

### ISSUE THREAD

**Issue by FolkvangrForgent** [reonZ/pf2e-toolbelt#68]
The Template Helper does not seem to currently support gridless and hex maps.  The dialogue option pops up but it has no effect. I would love to see the functionality extend to support all default grid options.

**Comment by reonZ** [comment]
sorry but pf2e combat is meant to be played on square grid, a lot of system mechanics don't even work without a square grid.

if anything i should prevent the popup from appearing.

**Comment by FolkvangrForgent** [comment]
Ah okay, I would assume the only thing from preventing it working on non square grids is this line in your library. https://github.com/reonZ/foundry-pf2e/blob/7c475d6a09300f1d23703b7bff81d7ed9b5f77c9/src/template.ts#L17

**Comment by reonZ** [comment]
No, this would require a different calculation.

**Comment by FolkvangrForgent** [comment]
I was able to throw some code together that works for both hex and square grids. Unfortunately gridHighlight on gridless does not seem to have positions (which makes sense) so I don't have a good solution for that. The idea behind this code is instead of calculating the positions of the token to instead iterate the positions of the gridHighlights for the token shapes
```
// parse positions from string on offset to center
gridHighlightPositions = []
for (const position of gridHighlight.positions) {
    position_x = parseFloat(position.split(',')[0]) + (canvas.grid.size / 2)
    position_y = parseFloat(position.split(',')[1]) + (canvas.grid.size / 2)
    gridHighlightPositions.push([position_x, position_y])
}

// iterate over tokens checking if any points lie within shape
for (const token of tokens) {
    for (const position of gridHighlightPositions) {
        position_x = position[0] - token.position.x;
        position_y = position[1] - token.position.y;
        if (token.shape.contains(position_x, position_y)) {
            containedTokens.push(token);
            break;
        }
    }
}
```

**Comment by SilverLous** [comment]
Hi, I'd also like that feature on a hex grid!

But I just want to comment on:

> sorry but pf2e combat is meant to be played on square grid, a lot of system mechanics don't even work without a square grid.
> 
> if anything i should prevent the popup from appearing.

From: https://2e.aonprd.com/Rules.aspx?ID=2558

> Hex Grids
Some of the challenges of diagonal movement can be fixed by using a hex grid instead of a square grid, or by using a grid with offset squares, which works similarly. This allows you to count movement the same in all directions. However, it makes flanking a bit harder to pull off, requires you to arrange standard Large and larger miniatures differently, and causes challenges when drawing maps that consist primarily of rectangular structures since you'll have a lot of partially occupied hexes.

PF2e works mostly fine if not better on a hex grid imo.

**Comment by FolkvangrForgent** [comment]
Hey @SilverLous,
I am developing a hex module (pf2e-hex) for the PF2e (and SF2e when it is released) system. As such I'll be incorporating this feature into my module in the near future. I have an open issue at the moment that contains a macro but it should eventually be as seamless as pf2e-toolbelt makes it.
- Forgent
